"""
Fee Receipt PDF Generator — renders receipt as HTML then converts to PDF.

Usage:
    from app.modules.fees.services.receipt_pdf import generate_receipt_pdf
    pdf_bytes = await generate_receipt_pdf(receipt)
"""

import html
from urllib.parse import urlsplit

from starlette.concurrency import run_in_threadpool

from app.db.models.fee import FeeReceipt
from app.shared.pdf_renderer import render_pdf


def _safe_logo_url(url: str | None) -> str | None:
    """Allow only http(s) logo URLs, escaped for the src attribute; otherwise drop the logo."""
    if not url:
        return None
    try:
        scheme = urlsplit(url).scheme.lower()
    except ValueError:
        return None
    if scheme not in ("http", "https"):
        return None
    return html.escape(url, quote=True)


def render_receipt_html(receipt: FeeReceipt, *, include_remote_logo: bool = True) -> str:
    """Render receipt as styled HTML. All school/student-controlled fields are escaped."""

    def e(value) -> str:
        return html.escape(str(value)) if value else ""

    school_name = e(receipt.school_name)
    school_address = e(receipt.school_address)
    school_contact = e(receipt.school_contact)
    student_name = e(receipt.student_name)
    class_name = e(receipt.class_name)
    fee_type = e(receipt.fee_type)
    receipt_number = e(receipt.receipt_number)
    transaction_id = e(receipt.transaction_id)
    # HTML previews may load the school's configured logo in the user's browser.
    # Server-side PDF rendering deliberately omits it: fetching a tenant-provided
    # URL from the API process would create an SSRF primitive.
    logo = _safe_logo_url(receipt.school_logo_url) if include_remote_logo else None
    paid_at = receipt.paid_at.strftime("%d-%b-%Y %I:%M %p") if receipt.paid_at else ""
    payment_mode = (
        receipt.payment_mode.value.replace("_", " ").title() if receipt.payment_mode else ""
    )
    transaction_row = (
        '<span class="label">Transaction ID:</span>'
        f'<span class="value">{transaction_id}</span>'
        if transaction_id
        else ""
    )

    return f"""<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
    @page {{ size: A5; margin: 15mm; }}
    body {{ font-family: 'Segoe UI', Arial, sans-serif; color: #1a1a1a; margin: 0; padding: 20px; }}
    .receipt {{
        border: 2px solid #2563eb; border-radius: 12px;
        padding: 24px; max-width: 500px; margin: auto;
    }}
    .header {{
        text-align: center; border-bottom: 2px solid #e5e7eb;
        padding-bottom: 16px; margin-bottom: 16px;
    }}
    .school-logo {{ width: 60px; height: 60px; border-radius: 50%; margin-bottom: 8px; }}
    .school-name {{ font-size: 18px; font-weight: 700; color: #1e40af; margin: 4px 0; }}
    .school-address {{ font-size: 12px; color: #6b7280; }}
    .receipt-title {{
        background: #2563eb; color: white; text-align: center;
        padding: 8px; border-radius: 6px; margin: 12px 0; font-weight: 600;
    }}
    .details {{ display: grid; grid-template-columns: 1fr 1fr; gap: 8px 16px; font-size: 13px; }}
    .label {{ color: #6b7280; font-weight: 500; }}
    .value {{ font-weight: 600; text-align: right; }}
    .amount-row {{
        border-top: 2px solid #2563eb; margin-top: 16px; padding-top: 12px;
        display: flex; justify-content: space-between;
        font-size: 18px; font-weight: 700; color: #059669;
    }}
    .footer {{ text-align: center; margin-top: 20px; font-size: 11px; color: #9ca3af; }}
    .stamp {{ text-align: right; margin-top: 24px; font-style: italic; color: #6b7280; }}
</style>
</head>
<body>
<div class="receipt">
    <div class="header">
        {f'<img class="school-logo" src="{logo}" alt="Logo">' if logo else ''}
        <div class="school-name">{school_name}</div>
        <div class="school-address">{school_address} | {school_contact}</div>
    </div>

    <div class="receipt-title">FEE RECEIPT</div>

    <div class="details">
        <span class="label">Receipt No:</span>
        <span class="value">{receipt_number}</span>

        <span class="label">Date:</span>
        <span class="value">{paid_at}</span>

        <span class="label">Student:</span>
        <span class="value">{student_name}</span>

        <span class="label">Class:</span>
        <span class="value">{class_name}</span>

        <span class="label">Fee Type:</span>
        <span class="value">{fee_type}</span>

        <span class="label">Payment Mode:</span>
        <span class="value">{payment_mode}</span>

        {transaction_row}
    </div>

    <div class="amount-row">
        <span>Amount Paid</span>
        <span>₹ {receipt.amount_paid:,.2f}</span>
    </div>

    <div class="stamp">Authorized Signatory</div>

    <div class="footer">
        This is a computer-generated receipt. No signature required.<br>
        Generated by StudyNexs Platform
    </div>
</div>
</body>
</html>"""


async def generate_receipt_pdf(receipt: FeeReceipt) -> bytes:
    """Generate real PDF bytes from a fee receipt or raise ``PDFRenderError``."""

    html_str = render_receipt_html(receipt, include_remote_logo=False)
    return await run_in_threadpool(
        render_pdf,
        html_str,
        document_type="fee_receipt",
    )


async def generate_receipt_html(receipt: FeeReceipt) -> str:
    """Return receipt as styled HTML string (for email/preview)."""
    return render_receipt_html(receipt)
